### ISSUE TITLE
POSTのエラー

### ISSUE THREAD

**Issue by Kazuma7** [u-lab/safety-park#18]
[入力値]
{
  "park_id": 5,
  "number_of_people": 1,
  "longitude": 0,
  "latitude": 0,
  "time_diff": 60,
  "start_time": "2020-07-23T01:00:26.662Z",
  "end_time": "2020-07-23T01:01:26.662Z"
}

[エラー文]

500 | Error: Internal Server Error

{
  "message": "SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '2020-07-23T01:00:26.662Z' for column `safety-park`.`user_locations`.`start_time` at row 1 (SQL: insert into `user_locations` (`park_id`, `number_of_people`, `longitude`, `latitude`, `time_diff`, `start_time`, `end_time`, `user_id`, `updated_at`, `created_at`) values (5, 1, 0, 0, 60, 2020-07-23T01:00:26.662Z, 2020-07-23T01:01:26.662Z, 1, 2020-07-23 10:20:29, 2020-07-23 10:20:29))",
  "exception": "Illuminate\\Database\\QueryException",
  "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Database/Connection.php",
  "line": 671,
  "trace": [
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Database/Connection.php",
      "line": 631,
      "function": "runQueryCallback",
      "class": "Illuminate\\Database\\Connection",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Database/Connection.php",
      "line": 465,
      "function": "run",
      "class": "Illuminate\\Database\\Connection",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Database/Connection.php",
      "line": 417,
      "function": "statement",
      "class": "Illuminate\\Database\\Connection",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php",
      "line": 32,
      "function": "insert",
      "class": "Illuminate\\Database\\Connection",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php",
      "line": 2772,
      "function": "processInsertGetId",
      "class": "Illuminate\\Database\\Query\\Processors\\Processor",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php",
      "line": 1403,
      "function": "insertGetId",
      "class": "Illuminate\\Database\\Query\\Builder",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php",
      "line": 900,
      "function": "__call",
      "class": "Illuminate\\Database\\Eloquent\\Builder",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php",
      "line": 865,
      "function": "insertAndSetId",
      "class": "Illuminate\\Database\\Eloquent\\Model",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php",
      "line": 728,
      "function": "performInsert",
      "class": "Illuminate\\Database\\Eloquent\\Model",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php",
      "line": 767,
      "function": "save",
      "class": "Illuminate\\Database\\Eloquent\\Model",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Support/helpers.php",
      "line": 433,
      "function": "Illuminate\\Database\\Eloquent\\{closure}",
      "class": "Illuminate\\Database\\Eloquent\\Builder",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php",
      "line": 768,
      "function": "tap"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php",
      "line": 23,
      "function": "create",
      "class": "Illuminate\\Database\\Eloquent\\Builder",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php",
      "line": 1732,
      "function": "forwardCallTo",
      "class": "Illuminate\\Database\\Eloquent\\Model",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php",
      "line": 1744,
      "function": "__call",
      "class": "Illuminate\\Database\\Eloquent\\Model",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/app/Http/Controllers/Api/UserLocationController.php",
      "line": 35,
      "function": "__callStatic",
      "class": "Illuminate\\Database\\Eloquent\\Model",
      "type": "::"
    },
    {
      "function": "create",
      "class": "App\\Http\\Controllers\\Api\\UserLocationController",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Routing/Controller.php",
      "line": 54,
      "function": "call_user_func_array"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php",
      "line": 45,
      "function": "callAction",
      "class": "Illuminate\\Routing\\Controller",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
      "line": 239,
      "function": "dispatch",
      "class": "Illuminate\\Routing\\ControllerDispatcher",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
      "line": 196,
      "function": "runController",
      "class": "Illuminate\\Routing\\Route",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
      "line": 685,
      "function": "run",
      "class": "Illuminate\\Routing\\Route",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
      "line": 128,
      "function": "Illuminate\\Routing\\{closure}",
      "class": "Illuminate\\Routing\\Router",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/app/Http/Middleware/ExsitTokenMiddleware.php",
      "line": 30,
      "function": "Illuminate\\Pipeline\\{closure}",
      "class": "Illuminate\\Pipeline\\Pipeline",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
      "line": 167,
      "function": "handle",
      "class": "App\\Http\\Middleware\\ExsitTokenMiddleware",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php",
      "line": 41,
      "function": "Illuminate\\Pipeline\\{closure}",
      "class": "Illuminate\\Pipeline\\Pipeline",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
      "line": 167,
      "function": "handle",
      "class": "Illuminate\\Routing\\Middleware\\SubstituteBindings",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php",
      "line": 59,
      "function": "Illuminate\\Pipeline\\{closure}",
      "class": "Illuminate\\Pipeline\\Pipeline",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
      "line": 167,
      "function": "handle",
      "class": "Illuminate\\Routing\\Middleware\\ThrottleRequests",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
      "line": 103,
      "function": "Illuminate\\Pipeline\\{closure}",
      "class": "Illuminate\\Pipeline\\Pipeline",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
      "line": 687,
      "function": "then",
      "class": "Illuminate\\Pipeline\\Pipeline",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
      "line": 662,
      "function": "runRouteWithinStack",
      "class": "Illuminate\\Routing\\Router",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
      "line": 628,
      "function": "runRoute",
      "class": "Illuminate\\Routing\\Router",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
      "line": 617,
      "function": "dispatchToRoute",
      "class": "Illuminate\\Routing\\Router",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
      "line": 165,
      "function": "dispatch",
      "class": "Illuminate\\Routing\\Router",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
      "line": 128,
      "function": "Illuminate\\Foundation\\Http\\{closure}",
      "class": "Illuminate\\Foundation\\Http\\Kernel",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
      "line": 21,
      "function": "Illuminate\\Pipeline\\{closure}",
      "class": "Illuminate\\Pipeline\\Pipeline",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
      "line": 167,
      "function": "handle",
      "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
      "line": 21,
      "function": "Illuminate\\Pipeline\\{closure}",
      "class": "Illuminate\\Pipeline\\Pipeline",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
      "line": 167,
      "function": "handle",
      "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php",
      "line": 27,
      "function": "Illuminate\\Pipeline\\{closure}",
      "class": "Illuminate\\Pipeline\\Pipeline",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
      "line": 167,
      "function": "handle",
      "class": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php",
      "line": 63,
      "function": "Illuminate\\Pipeline\\{closure}",
      "class": "Illuminate\\Pipeline\\Pipeline",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
      "line": 167,
      "function": "handle",
      "class": "Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/fruitcake/laravel-cors/src/HandleCors.php",
      "line": 57,
      "function": "Illuminate\\Pipeline\\{closure}",
      "class": "Illuminate\\Pipeline\\Pipeline",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
      "line": 167,
      "function": "handle",
      "class": "Fruitcake\\Cors\\HandleCors",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/fideloper/proxy/src/TrustProxies.php",
      "line": 57,
      "function": "Illuminate\\Pipeline\\{closure}",
      "class": "Illuminate\\Pipeline\\Pipeline",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
      "line": 167,
      "function": "handle",
      "class": "Fideloper\\Proxy\\TrustProxies",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
      "line": 103,
      "function": "Illuminate\\Pipeline\\{closure}",
      "class": "Illuminate\\Pipeline\\Pipeline",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
      "line": 140,
      "function": "then",
      "class": "Illuminate\\Pipeline\\Pipeline",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
      "line": 109,
      "function": "sendRequestThroughRouter",
      "class": "Illuminate\\Foundation\\Http\\Kernel",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/public/index.php",
      "line": 55,
      "function": "handle",
      "class": "Illuminate\\Foundation\\Http\\Kernel",
      "type": "->"
    },
    {
      "file": "/Users/kazuma.i/Documents/GitHub/safety-park/api/server.php",
      "line": 21,
      "function": "require_once"
    }
  ]
}

**Comment by Usuyuki** [comment]
Swaggerのデフォルトの時刻"2020-07-23T01:00:26.662Z"表記ではなく"2020-07-18 17:25:37"のような表記、または""だとエラーでないかと思われます。
yamlファイルでは
`            type: string
            format: 'date-time'`
と記載してSQLの型に合わせてますが、こうするとデフォルト値が"2020-07-23T01:00:26.662Z"の形になってしまうみたいです。
